version: "2.1"
services:
  nginx:
    build:
      dockerfile: ./config/docker/nginx/Dockerfile
      context: .
    container_name: blog_nginx
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - fpm
    ports:
      - ${NGINX_PORT:-88}:80
  fpm:
    build:
      dockerfile: ./config/docker/fpm/Dockerfile
      context: .
    container_name: blog_php
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - pgsql
  pgsql:
    image: fintrace/postgres-uuid
    container_name: blog_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-blog}