version: "2.1"
services:
    code:
        image: hub.mazanax.ru/blog_code:latest
        container_name: blog_code
        depends_on:
            - pgsql
    nginx:
        image: hub.mazanax.ru/blog_nginx:latest
        container_name: blog_nginx
        depends_on:
          - code
        volumes:
          - ../uploads:/var/www/html/public/uploads
        volumes_from:
            - code:ro
        links:
            - fpm
        ports:
            - ${NGINX_PORT:-80}:80
    fpm:
        image: hub.mazanax.ru/blog_php:latest
        environment:
            - APP_ENV=prod
            - APP_SECRET=${APP_SECRET:-33b1ff8771c53a5fd36061f5b42a0328}
            - POSTGRES_USER=${POSTGRES_USER:-root}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
            - POSTGRES_DB=${POSTGRES_DB:-blog}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
        container_name: blog_php
        restart: always
        depends_on:
            - code
        volumes:
            - ../uploads:/var/www/html/public/uploads
        volumes_from:
            - code
        links:
            - pgsql
    pgsql:
        image: fintrace/postgres-uuid
        container_name: blog_postgres
        restart: always
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - ../pgsql:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-root}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
            - POSTGRES_DB=${POSTGRES_DB:-blog}