# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  on_page: '%env(int:ON_PAGE)%'
  allowed_mime_types:
    - image/jpeg
    - image/gif
    - image/svg+xml
    - image/webp
    - image/png
    - image/apng

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $onPage: '%on_page%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Validation\Validator\ValidatorInterface: '@App\Validation\Validator\Validator'

  App\Component\PostGetter\PostGetter:
    arguments:
      - '@App\Component\PostGetter\PublishedPostGetterStrategy'
      - '@App\Component\PostGetter\ScheduledPostGetterStrategy'

  App\Component\PostListTitleGetter\PostListTitleGetter:
    arguments:
      - '@App\Component\PostListTitleGetter\PublishedPostListTitleStrategy'
      - '@App\Component\PostListTitleGetter\ScheduledPostListTitleStrategy'

  App\Component\PostListTitleGetter\PostListTitleGetterInterface: '@App\Component\PostListTitleGetter\PostListTitleGetter'

  App\Component\FileUploader\FileStorage\LocalStorage:
    arguments:
      $uploadsDir: '%kernel.project_dir%/public/uploads'
      $publicPath: '/uploads'

  App\Component\FileUploader\FileUploader:
    arguments:
      $allowedMimeTypes: '%allowed_mime_types%'

  App\Component\FileUploader\FileUploaderInterface: '@App\Component\FileUploader\UniqueFileUploader'

  App\Component\Menu\Factory\ItemFactory:
    arguments:
      - '@App\Component\Menu\Factory\Item\ExternalItemFactory'
      - '@App\Component\Menu\Factory\Item\FolderItemFactory'
      - '@App\Component\Menu\Factory\Item\PageItemFactory'
      - '@App\Component\Menu\Factory\Item\TagItemFactory'

  App\Component\Menu\Factory\ItemDTOFactory:
    arguments:
      - '@App\Component\Menu\Factory\ItemDTO\ExternalDTOFactory'
      - '@App\Component\Menu\Factory\ItemDTO\FolderDTOFactory'
      - '@App\Component\Menu\Factory\ItemDTO\PageDTOFactory'
      - '@App\Component\Menu\Factory\ItemDTO\TagDTOFactory'